### ISSUE TITLE
Choco install is not working

### ISSUE THREAD

**Issue by Rage65** [PowerPCFan/UltimateWindowsToolbox#4]
When it installs choco choco is not installed when I press a key to continue the script crashes and trying to run choco in the commandline results in a command not found. My guess is either the choco install script is not being run as intended leading to a error or choco is not being added to PATH

**Comment by PowerPCFan** [comment]
My guess is that this has to do with the fact that Chocolatey/choco doesn't usually work when you install it and then try to run it in an already opened Terminal or the same one you installed it in. Not sure how I'd make the terminal "refresh" after installing though... maybe have it relaunch the script after running it? what do you think?

**Comment by Rage65** [comment]
> My guess is that this has to do with the fact that Chocolatey/choco doesn't usually work when you install it and then try to run it in an already opened Terminal or the same one you installed it in. Not sure how I'd make the terminal "refresh" after installing though... maybe have it relaunch the script after running it? what do you think?

It's still not working after reboot

**Comment by PowerPCFan** [comment]
I wonder if chocolatey failed to install - I made it so the commands run in a new window so you shouldn't run into any issues, I tested on a fresh Windows 10 and Windows 11 VM and there weren't any issues... can you try removing the folder C:\ProgramData\Chocolatey and run the script again? Also during testing I discovered another issue causing the script to install like 10 apps that you didn't select so I'll have to fix that!

**Comment by Rage65** [comment]
> I wonder if chocolatey failed to install - I made it so the commands run in a new window so you shouldn't run into any issues, I tested on a fresh Windows 10 and Windows 11 VM and there weren't any issues... can you try removing the folder C:\ProgramData\Chocolatey and run the script again? Also during testing I discovered another issue causing the script to install like 10 apps that you didn't select so I'll have to fix that!

Yeah the chocolaty folder was there but empty so I assume it just looks if the filder is there if installing. After deleting and retuning the script it seems to be working 🤞

**Comment by Rage65** [comment]
It worked but it apeears to get stuck at extracting and you have to press ctrl + c after a minute then it continues to install normally

**Comment by PowerPCFan** [comment]
Ok, i'll try to fix that issue and also fix the unwanted programs issue and maybe add a "repair chocolatey" option that deletes and reinstalls it??

**Comment by PowerPCFan** [comment]
@Rage65 I think i fixed the issues would you mind testing again?

**Comment by Rage65** [comment]
****

> @Rage65 I think i fixed the issues would you mind testing again?

Everything seems to be working well

**Comment by PowerPCFan** [comment]
That's good, feel free to open an issue again if you find any more bugs (this goes for anyone else coming across this repo as well lol)
